---
- hosts: riakservers
  sudo: True
  tasks:
  - name: stopping riak
    service: name=riak state=stopped
    ignore_errors: True
  - name: kill epmd
    command: pkill -u riak
- hosts: riakservers
  sudo: True
  tasks:
  - name: purge riak support file $item
    file: path=$item state=absent
    with_items:
      - /var/lib/riak/bitcask
      - /var/lib/riak/eleveldb
    ignore_errors: True
  - name: starting riak
    service: name=riak state=started
- hosts: riaklast
  sudo: True
  tasks:
  - name: wait for transfers to complete
    riak: ip=$node_ip host_list=${groups.riakservers} transfer_wait=true
    async: 300
    poll: 10